fix: Make contracts file resolvable during build (#28)
* fix(build): Make contracts file resolvable during build

* fix(contracts): Move addresses file into bindings

* fix(build): Fix error message

* fix(build): Ensure out dir exists

* fix(build): Correct path display

* fix(test): Add contracts file as readable

diff --git a/ethereum/contracts/Makefile b/ethereum/contracts/Makefile
--- a/ethereum/contracts/Makefile
+++ b/ethereum/contracts/Makefile
@@ -286,7 +286,7 @@ ensure-network-is-set:
 ifeq ($(network),)
 	echo "parameter <network> missing" >&2 && exit 1
 else
-environment-type != jq '.networks."$(network)".environment_type // empty' contracts-addresses.json
+environment-type != jq '.networks."$(network)".environment_type // empty' ../bindings/contracts-addresses.json
 endif
 
 .PHONY: ensure-etherscan-api-key-is-set
@@ -300,7 +300,7 @@ endif
 
 ensure-environment-is-set:
 ifeq ($(environment-type),)
-	echo "could not read environment info from contracts-addresses.json" >&2 && exit 1
+	echo "could not read environment info from ../bindings/contracts-addresses.json" >&2 && exit 1
 endif
 
 ensure-privatekey-is-set:
